sudo: required

language: python

services:
  - docker
  
before_install:
  - docker build -t gyzpunk/readthedocs .

script:
  - docker run --entrypoint=bash gyzpunk/readthedocs -ec "echo Build succeed"
