sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t gyzpunk/readthedocs .
  - docker run -d --name rtfd gyzpunk/readthedocs
  - docker ps -a

deploy:
  - provider: script
    script: "curl -H \"Content-Type: application/json\" --data '{\"build\": true}' -X POST https://registry.hub.docker.com/u/${TRAVIS_REPO_SLUG}/trigger/${DOCKER_TOKEN}/"
    on:
      branch: master

script:
  - docker exec rtfd echo Build succeed
