sudo: required

language: python

services:
  - docker

before_install:
  - docker build -t gyzpunk/readthedocs .
  - docker run -d --name rtfd gyzpunk/readthedocs
  - docker ps -a

deploy:
  provider: script
    script: docker_deploy.sh
    on:
      branch: master

script:
  - docker exec rtfd echo Build succeed
