sudo: required

language: python

services:
  - docker
  
before_install:
  - docker build -t gyzpunk/readthedocs .
  - docker ps -a

script:
  - docker run --entrypoint=bash gyzpunk/readthedocs -ec "echo Build succeed"'
